services:
  dryft-api:
    image: dryft-api:latest
    restart: always
    env_file:
      - .env.local
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dryft-api.rule=Host(`api.dryft.ca`)"
      - "traefik.http.routers.dryft-api.entrypoints=websecure"
      - "traefik.http.routers.dryft-api.tls=true"
      - "traefik.http.routers.dryft-api.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"


