// biome-ignore assist/source/organizeImports: react-scan
import { ReactScan } from "@/lib/react-scan";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { GlobalDrawer } from "@/components/global-drawer";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactScan />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <GlobalDrawer />
        </Providers>
      </body>
    </html>
  );
}
