name: dryft
services:
  dryft-api:
    container_name: dryft-api
    image: ghcr.io/shahbaz-athwal/dryft-api:latest
    environment:
      - PORT=4000
      - DATABASE_URL
      - NODE_ENV=production
      - FRONTEND_URL
      - BETTER_AUTH_SECRET
      - ACADIA_USERNAME
      - ACADIA_PASSWORD
    command: "bun run api:start"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dryft-api.rule=Host(`api.dryft.ca`)"
      - "traefik.http.routers.dryft-api.entrypoints=websecure"
      - "traefik.http.routers.dryft-api.tls=true"
      - "traefik.http.routers.dryft-api.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - postgres

  drift-api-dev:
    container_name: drift-api-dev
    image: ghcr.io/shahbaz-athwal/drift-api:latest
    environment:
      - PORT=4000
      - DEV_DATABASE_URL
      - NODE_ENV=development
      - FRONTEND_URL
      - BETTER_AUTH_SECRET
      - ACADIA_USERNAME
      - ACADIA_PASSWORD
    command: "bun run api:start"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.drift-api-dev.rule=Host(`api-dev.dryft.ca`)"
      - "traefik.http.routers.drift-api-dev.entrypoints=websecure"
      - "traefik.http.routers.drift-api-dev.tls=true"
      - "traefik.http.routers.drift-api-dev.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - postgres
