name: dryft
services:
  dryft-api:
    container_name: dryft-api-prod
    image: ghcr.io/shahbaz-athwal/dryft-api-prod:latest
    environment:
      - PORT=4000
      - DATABASE_URL
      - NODE_ENV=production
      - FRONTEND_URL
      - BETTER_AUTH_SECRET
      - ACADIA_USERNAME
      - ACADIA_PASSWORD
    command: "bun run api:start"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dryft-api-prod.rule=Host(`api.dryft.ca`)"
      - "traefik.http.routers.dryft-api-prod.entrypoints=websecure"
      - "traefik.http.routers.dryft-api-prod.tls=true"
      - "traefik.http.routers.dryft-api-prod.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - db-prod
      - monitoring
